; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Menu Tray, Icon, shell32.dll, 14

Gui Main: New, +LabelMain +hWndhWndMain +ToolWindow
Gui Font, s9, Segoe UI
Gui Add, Radio, hWndCSV_export vCSV_export gCSV_export x32 y16 w120 h23, CSV export
Gui Add, Radio, hWndhRadJsonn2 vRadJsonn2 gJsonx x32 y56 w138 h23, Json_export
Gui Add, Radio, hWndhRadSql3 vRadSql3 gSQLite x32 y96 w120 h23, SQLite export
Gui Add, Button, hWndhBtnGo_baby_go vBtnGo_baby_go gGo_Baby_Go x40 y152 w80 h23, Go_Baby_Go

Gui Show, w228 h226, Steam_Library_Export
Return

CSV_export(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

Jsonx(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

SQLite(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

Go_Baby_Go(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

MainEscape(GuiHwnd) {
    ExitApp
}

MainClose(GuiHwnd) {
    ExitApp
}
